# GitVote chart default configuration values

imagePullSecrets: []
imageTag: ""
nameOverride: ""
pullPolicy: IfNotPresent

# Enable dynamic resource name prefix
#
# Enabling the dynamic resource name prefix ensures that the resources are named dynamically based on the Helm
# installation's name. This allows multiple installations of this chart in a single Kubernetes namespace. The prefix
# can be defined by using the `fullnameOverride`.
dynamicResourceNamePrefixEnabled: false

# Overwrites the installation's fullname generation (used for the dynamic resource name prefix)
fullnameOverride: ""

# Directory path where the configuration files should be mounted
configDir: "/home/gitvote/.config/gitvote"

# Database configuration
db:
  host: ""
  port: "5432"
  dbname: gitvote
  user: postgres
  password: postgres

# Database migrator configuration
dbmigrator:
  job:
    image:
      # Database migrator image repository (without the tag)
      repository: dbmigrator

# GitVote service configuration
gitvote:
  # Address to listen on
  addr: 0.0.0.0:9000

  # GitHub configuration
  github:
    # GitHub application ID
    appID: null
    # GitHub application private key path
    appPrivateKey: null

  # Ingress configuration
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    rules: []
    tls: []

  # Service configuration
  service:
    type: NodePort
    port: 80

  # Deployment configuration
  deploy:
    replicaCount: 1
    image:
      repository: gitvote
    resources: {}

# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository: artifacthub/postgres
    tag: latest
  persistence:
    mountPath: /data
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: gitvote
  postgresqlDataDir: /data/pgdata
