# GitVote chart default configuration values

imagePullSecrets: []
imageTag: ""
nameOverride: ""
pullPolicy: IfNotPresent

# Enable dynamic resource name prefix
#
# Enabling the dynamic resource name prefix ensures that the resources are named dynamically based on the Helm
# installation's name. This allows multiple installations of this chart in a single Kubernetes namespace. The prefix
# can be defined by using the `fullnameOverride`.
dynamicResourceNamePrefixEnabled: false

# Overwrites the installation's fullname generation (used for the dynamic resource name prefix)
fullnameOverride: ""

# Directory path where the configuration files should be mounted
configDir: "/home/gitvote/.config/gitvote"

# Check database readiness init container configuration
checkDbIsReadyInitContainer:
  securityContext: {}

# Database configuration
db:
  host: ""
  port: "5432"
  dbname: gitvote
  password: gitvote
  user: gitvote

# Log configuration
log:
  # Output format [json|pretty]
  format: json

# Database migrator configuration
dbmigrator:
  job:
    containerSecurityContext: {}
    image:
      # Database migrator image repository (without the tag)
      repository: ghcr.io/cncf/gitvote/dbmigrator
    podSecurityContext: {}

# GitVote service configuration
gitvote:
  # Address to listen on
  addr: 0.0.0.0:9000

  # GitHub configuration
  #
  # For more information about the permissions and events required please see
  # the chart's readme file.
  github:
    # GitHub application ID
    appID: null
    # GitHub application private key path
    appPrivateKey: null
    # GitHub application webhook secret
    webhookSecret: null
    # GitHub application webhook secret fallback (handy for webhook secret rotation)
    webhookSecretFallback: null

  # Ingress configuration
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    backendServicePort: 80
    rules: []
    tls: []

  # Service configuration
  service:
    allocateLoadBalancerNodePorts: true
    annotations: {}
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 9000
    type: NodePort

  # Deployment configuration
  deploy:
    containerSecurityContext: {}
    image:
      repository: ghcr.io/cncf/gitvote/server
    podSecurityContext: {}
    readinessProbe:
      httpGet:
        path: /
        port: 9000
    replicaCount: 1
    resources: {}

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    database: gitvote
    password: gitvote
    username: gitvote
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: artifacthub/postgres
    tag: latest
  persistence:
    mountPath: /data
  primary:
    extraVolumes:
      - name: run
        emptyDir: {}
    extraVolumeMounts:
      - name: run
        mountPath: /var/run/postgresql
