[package]
name = "gitvote"
description = "GitVote server"
version = "1.5.0"
license = "Apache-2.0"
edition = "2024"
rust-version = "1.96.1"

[dependencies]
anyhow = "1.0.103"
askama = { version = "0.16.0", features = ["serde_json"] }
async-channel = "2.5.0"
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["macros"] }
cached = { version = "2.0.2", features = ["async"] }
clap = { version = "4.6.1", features = ["derive"] }
deadpool-postgres = { version = "0.14.1", features = ["serde"] }
figment = { version = "0.10.19", features = ["yaml", "env"] }
futures = "0.3.32"
graphql_client = { version = "0.16.0", features = ["reqwest-rustls"] }
hex = "0.4.3"
hmac = "0.13.0"
http = "1.4.2"
humantime = "2.3.0"
humantime-serde = "1.1.1"
ignore = "0.4.27"
jsonwebtoken = { version = "10.4.0", default-features = false, features = [
    "aws_lc_rs",
    "use_pem",
] }
octocrab = { version = "0.53.1", default-features = false, features = [
    "default-client",
    "follow-redirect",
    "jwt-aws-lc-rs",
    "retry",
    "rustls",
    "rustls-aws-lc-rs",
    "timeout",
    "tracing",
] }
regex = "1.12.4"
reqwest = "0.13.4"
rustls = "0.23.41"
rustls-platform-verifier = "0.7.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_yaml = "0.9.34"
sha2 = "0.11.0"
thiserror = "2.0.18"
time = { version = "0.3.53", features = ["serde"] }
tokio = { version = "1.52.3", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "time",
] }
tokio-postgres = { version = "0.7.18", features = [
    "with-uuid-1",
    "with-serde_json-1",
    "with-time-0_3",
] }
tokio-postgres-rustls = "0.14.0"
tokio-util = { version = "0.7.18", features = ["rt"] }
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
uuid = { version = "1.23.4", features = ["serde", "v4"] }

[dev-dependencies]
http-body = "1.0.1"
hyper = "1.10.1"
mockall = "0.15.0"
