# GitVote metadata file
# This file must be located at the root of the repository

# Voters (required)
# List of GitHub usernames of the users who have binding votes
voters:
  - tegioz
  - cynthia-sg

# Pass threshold (required)
# Percentage of votes required to pass the vote
pass_threshold: 67

# Voting duration (required)
# How long the vote will be open
#
# Units supported (can be combined as in 1hour 30mins):
#
#   minutes | minute | mins | min | m
#   hours   | hour   | hrs  | hrs | h
#   days    | day    | d
#   weeks   | week   | w
#
duration: 5m
