# GitVote configuration file
# This file must be located at the root of the repository

# Voting duration (required)
# How long the vote will be open
#
# Units supported (can be combined as in 1hour 30mins):
#
#   minutes | minute | mins | min | m
#   hours   | hour   | hrs  | hrs | h
#   days    | day    | d
#   weeks   | week   | w
#
duration: 5m

# Pass threshold (required)
# Percentage of votes in favor required to pass the vote
pass_threshold: 50

# Allowed voters (optional)
# List of GitHub usernames of the users who have binding votes
#
# If the list is empty, all repository collaborators will be allowed to vote.
# For organization-owned repositories, the list of collaborators includes
# outside collaborators, organization members that are direct collaborators,
# organization members with access through team memberships, organization
# members with access through default organization permissions, and
# organization owners.
#
# allowed_voters:
#   - cynthia-sg
#   - tegioz
#
allowed_voters: []
