# GitVote configuration file
#
# GitVote will look for it in the following locations (in order of precedence):
#
#   - At the root of the repository where the vote was created
#   - At the root of the .github repository, for organization wide configuration
#

# Default configuration profile
#
# This profile will be used with votes created with the /vote command
default:
  # Voting duration (required)
  #
  # How long the vote will be open
  #
  # Units supported (can be combined as in 1hour 30mins):
  #
  #   minutes | minute | mins | min | m
  #   hours   | hour   | hrs  | hrs | h
  #   days    | day    | d
  #   weeks   | week   | w
  #
  duration: 5m

  # Pass threshold (required)
  #
  # Percentage of votes in favor required to pass the vote
  #
  # The percentage is calculated based on the number of votes in favor and the
  # number of allowed voters (see allowed_voters field below for more details).
  pass_threshold: 50

  # Allowed voters (optional)
  #
  # List of GitHub teams and users who have binding votes
  #
  # If no teams or users are provided, all repository collaborators will be
  # allowed to vote. For organization-owned repositories, the list of
  # collaborators includes outside collaborators, organization members that are
  # direct collaborators, organization members with access through team
  # memberships, organization members with access through default organization
  # permissions, and organization owners.
  #
  # Teams names must be provided without the organization prefix.
  #
  # allowed_voters:
  #   teams:
  #     - team1
  #   users:
  #     - cynthia-sg
  #     - tegioz
  #
  allowed_voters:
    teams: []
    users: []

# Additional configuration profiles
#
# In addition to the default configuration profile, it is possible to add more
# to easily create votes with different settings. To create a vote that uses a
# different profile you can use the command /vote-PROFILE. In the case below,
# the command would be /vote-profile1
#
# Please note that each profile must contain all required fields. The default
# profile is used when using the /vote command, but its values are not used as
# default values when they are not provided on other profiles.
#
profile1:
  duration: 1m
  pass_threshold: 75
  allowed_voters:
    teams:
      - team1
