{{- if .Values.gitvote.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}gitvote
  labels:
    app.kubernetes.io/component: gitvote
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.gitvote.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  defaultBackend:
    service:
      name: {{ include "chart.resourceNamePrefix" . }}gitvote
      port:
        number: {{ .Values.gitvote.service.port }}
  {{- with .Values.gitvote.ingress.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gitvote.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
